#!/usr/bin/env bash

_cruise_autocomplete() {
    local cursor prev_word commands options
    COMPREPLY=()
    cursor="${COMP_WORDS[COMP_CWORD]}"
    prev_word="${COMP_WORDS[COMP_CWORD-1]}"
    commands="environments build start stop restart status containers shell root-shell run export import remove create traefik code install uninstall"

    case "${prev_word}" in
        remove)
            COMPREPLY=( -v -a -f )
            
            return 0
            ;;
        build | stop)
            COMPREPLY=( -v -f )
            
            return 0
            ;;
        start)
            COMPREPLY=( -v -n -i -p -e -s -c -l -b )
            
            return 0
            ;;
        traefik)
            COMPREPLY=( -v -n -i -p -e -s -c -l -b )
            
            return 0
            ;;
        import)
            COMPREPLY=( $(compgen -f "${cursor}") )
            
            return 0
            ;;
        create | export | restart | code | run)
            COMPREPLY=( -v )
            
            return 0
            ;;
        shell)
            COMPREPLY=( -v -n -i -e -u -b )

            return 0
            ;;
        root-shell)
            COMPREPLY=( -v -n -i -e -b )

            return 0
            ;;
        uninstall)
            COMPREPLY=( -f )

            return 0
            ;;
        environments | status | install | uninstall | -f)
            COMPREPLY=()

            return 0
            ;;
        containers)
            COMPREPLY=( -a )

            return 0
            ;;
        -v)
            for keyword in build stop start traefik create export restart code shell root-shell run remove; do
                if [[ "${COMP_WORDS[@]}" = *"$keyword"* ]]; then
                    COMPREPLY=( $(ls "$HOME/.cruise/environments") )
                    break
                fi
            done

            return 0
            ;;
        -n)
            for keyword in start traefik shell root-shell; do
                if [[ "${COMP_WORDS[@]}" = *"$keyword"* ]]; then
                    COMPREPLY=( $(docker network ls --format "{{.Name}}") )
                    break
                fi
            done

            return 0
            ;;
        -f)
            for keyword in build stop; do
                if [[ "${COMP_WORDS[@]}" = *"$keyword"* ]]; then
                    COMPREPLY=( -v )
                    break
                fi
            done

            return 0
            ;;
        -s)
            for keyword in start traefik; do
                if [[ "${COMP_WORDS[@]}" = *"$keyword"* ]]; then
                    COMPREPLY=( nginx octane )
                    break
                fi
            done
            
            return 0
            ;;
        -u)
            for keyword in shell; do
                if [[ "${COMP_WORDS[@]}" = *"$keyword"* ]]; then
                    COMPREPLY=( cruise root )
                    break
                fi
            done
            
            return 0
            ;;
        *)
            COMPREPLY=( $(compgen -W "${commands}" -- ${cursor}) )
            
            return 0
            ;;
    esac
}

complete -F _cruise_autocomplete cruise
