#!/usr/bin/env bash

_traefik_autocomplete() {
    local cur prev cmd flags w i commands
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    commands="start stop restart status version install uninstall"

    cmd=""
    for ((i = 1; i < COMP_CWORD; i++)); do
        w="${COMP_WORDS[i]}"
        case " $commands " in
            *" $w "*)
                cmd="$w"
                break
                ;;
        esac
    done

    case "$cmd" in
        start)
            flags="-a -b"
            ;;
        stop | uninstall)
            flags="-f"
            ;;
        *)
            flags=""
            ;;
    esac

    case "$cur" in
        -*)
            COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
            return 0
            ;;
    esac

    if [[ -n "$cmd" ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
    elif [[ "$prev" != -* ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
    fi

    return 0
}

complete -F _traefik_autocomplete traefik
